// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 15.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FPLedit.Kursbuch.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class KfplTemplate : KfplTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!doctype html>\r\n<html>\r\n<head>\r\n<meta charset=\"utf-8\">\r\n<style>\r\nbody {\r\n\tfont" +
                    "-family:\"KBZiffern\",sans-serif;\r\n}\r\ntable {\r\n\tborder-collapse:\r\n\tcollapse;\r\n\tbor" +
                    "der:none;\r\n\tmargin-bottom: 20px;\r\n}\r\n.heading {\r\n\ttext-align:center;\r\n\tmargin-to" +
                    "p:0cm;\r\n\tmargin-right:0cm;\r\n\tmargin-bottom:8.0pt;\r\n\tmargin-left:0cm;\r\n\tline-heig" +
                    "ht:107%;\r\n\tfont-size:11.0pt;\r\n}\r\n.kmcap {\r\n\tborder:solid black 1.0pt;\r\n\tpadding:" +
                    "0;\r\n}\r\n.kmcap p {\r\n\tfont-size:9pt;\r\n\ttext-align:center;\r\n}\r\n.caption.top {\r\n\tbor" +
                    "der-top:solid black 1.0pt;\r\n}\r\n.caption.bottom {\r\n\tborder-bottom:solid black 1.0" +
                    "pt;\r\n}\r\n.caption {\r\n\tborder-right:solid black 1.5pt;\r\n\tpadding:0;\r\n}\r\n.caption p" +
                    " {\r\n\tmargin: 0;\r\n\tline-height:107%;\r\n\tfont-size:8.0pt;\r\n\ttext-align:right;\r\n\tlin" +
                    "e-height:normal;\r\n}\r\n.tn {\r\n\tborder-top:solid black 1.5pt;\r\n\tborder-right:solid " +
                    "black 1.0pt;\r\n\tpadding: 0 3px 0 3px;\r\n\ttext-align:center;\r\n}\r\n.kl {\r\n\tborder-bot" +
                    "tom:solid black 1pt;\r\n\tborder-right:solid black 1.0pt;\r\n\tpadding: 0 3px 0 3px;\r\n" +
                    "\ttext-align:center;\r\n}\r\n.ti {\r\n\tborder-right:solid black 1.0pt;\r\n\tpadding: 0 3px" +
                    " 0 3px;\r\n\ttext-align:center;\r\n}\r\n.ti.last {\r\n\tborder-bottom:solid black 1.5pt;\r\n" +
                    "}\r\n.sta {\r\n\tborder-right:solid black 1.5pt;\r\n\tpadding: 0 3px 0 3px;\r\n}\r\n.tn span" +
                    ", .kl span, .ti span {\r\n\tmargin: 0;\r\n\tfont-size:8.0pt;\r\n\tline-height:normal;\r\n}\r" +
                    "\n.sta span, .km span {\r\n\tmargin: 0;\r\n\tline-height:107%;\r\n\tfont-size:9.0pt;\r\n\tlin" +
                    "e-height:normal;\r\n}\r\n.sta.last, .km.last {\r\n\tborder-bottom:solid black 1pt;\r\n}\r\n" +
                    ".km {\r\n\tborder-left:solid black 1.0pt;\r\n\tborder-right:solid black 1.0pt;\r\n\tpaddi" +
                    "ng:0;\r\n}\r\n</style>\r\n</head>\r\n\r\n<body>\r\n<div>\r\n\r\n<p class=\"heading\">\r\n\t<span styl" +
                    "e=\'font-family:\"Arial Black\",sans-serif;font-weight:900; letter-spacing:-.5pt\'>2" +
                    "80 d ");
            
            #line 106 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tt.GetLineName(TOP_DIRECTION)));
            
            #line default
            #line hidden
            this.Write(" </span>\r\n\t<span style=\'letter-spacing:.5pt\'>und zurück</span>\r\n</p>\r\n");
            
            #line 109 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 foreach (var direction in new[] { TOP_DIRECTION, BOTTOM_DIRECTION }) {
	var trains = tt.Trains.Where(o => o.Direction == direction);
	var stations = tt.GetStationsOrderedByDirection(direction);

            
            #line default
            #line hidden
            this.Write("<table cellspacing=0 cellpadding=0>\r\n\t<tr>\r\n\t\t<td class=\"kmcap\" rowspan=2><p>km</" +
                    "span></td>\r\n\t\t<td class=\"caption top\"><p><span>Zug Nr.</span></p></td>\r\n\t\t");
            
            #line 117 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 foreach (var t in tt.Trains) {
            
            #line default
            #line hidden
            this.Write("\t\t<td class=\"tn\"><span>");
            
            #line 118 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sign(t)));
            
            #line default
            #line hidden
            
            #line 118 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.TName.Replace(" ", "&nbsp;")));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t");
            
            #line 119 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n\t<tr>\r\n\t\t<td class=\"caption bottom\"><p><span>Klasse   </span></p></td>\r\n\t" +
                    "\t");
            
            #line 123 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 foreach (var t in trains) {
            
            #line default
            #line hidden
            this.Write("\t\t<td class=\"kl\"><span>2. oG</span></td>\r\n\t\t");
            
            #line 125 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n\t");
            
            #line 127 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 foreach (var sta in stations) { 
            
            #line default
            #line hidden
            this.Write("\t<tr>\r\n\t\t");
            
            #line 129 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 var last = stations.Last() == sta ? " last" : ""; 
            
            #line default
            #line hidden
            this.Write("\t\t<td class=\"km");
            
            #line 130 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(last));
            
            #line default
            #line hidden
            this.Write("\"><span>");
            
            #line 130 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sta.Kilometre.ToString("0.0")));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t<td class=\"sta");
            
            #line 131 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(last));
            
            #line default
            #line hidden
            this.Write("\"><span>");
            
            #line 131 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sta.SName.Replace(" ", "&nbsp;")));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\r\n\t\t");
            
            #line 133 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 foreach (var t in trains) {
			var time = t.GetArrDep(sta).Departure.ToString(@"hh\:mm");
			if (time == "") time =  t.GetArrDep(sta).Arrival.ToString(@"hh\:mm");
			if (time == "") time = "...";
		
            
            #line default
            #line hidden
            this.Write("\t\t<td class=\"ti");
            
            #line 138 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(last));
            
            #line default
            #line hidden
            this.Write("\"><span>");
            
            #line 138 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(time));
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t");
            
            #line 139 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</tr>\r\n\t");
            
            #line 141 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 143 "F:\VS-Projects\Buchfahrplan\Buchfahrplan\FPLedit.Kursbuch\Templates\KfplTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</div>\r\n\r\n</body>\r\n\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class KfplTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
