//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPLedit.Aushangfahrplan.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FPLedit.Aushangfahrplan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; height=&quot;17.858mm&quot; width=&quot;96.157mm&quot; version=&quot;1.1&quot; viewBox=&quot;0 0 340.71493 63.276046&quot;&gt;
        ///&lt;g transform=&quot;translate(-1.7856 -1.0716)&quot; stroke=&quot;#000&quot; stroke-width=&quot;.25&quot; fill=&quot;#b24315&quot;&gt;
        ///&lt;path d=&quot;m37.713 1.3708c-0.075-0.1265-0.75-0.2361-1.062-0.1298-7.227 2.46-17.664 2.5891-20.971 2.7426-1.06-0.1349-1.718-0.3251-1.939 0.4879-0.95164 3.4987 0.20793 6.9768 3.379 6.8466 1.4645-0.0601 3.3757-0.84609 3.3026 1.515l-12.352 41.172 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string abfahrt_text {
            get {
                return ResourceManager.GetString("abfahrt_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;script&gt;
        ///// CSS-Tryout-Console , generiert von FPLedit
        ///var tryout_code = `&lt;style&gt;
        ///#tryout-console {
        ///	position:absolute;
        ///	top: 10px;
        ///	right: 10px;
        ///	border: 1px solid black;
        ///	padding: 10px;
        ///	background-color: white !important;
        ///}
        ///
        ///@media print {
        ///	#tryout-console {
        ///		display: none;
        ///	}
        ///}
        ///&lt;/style&gt;
        ///&lt;div id=&quot;tryout-console&quot;&gt;
        ///	Hier können Sie CSS-Code eingeben und testen:&lt;br&gt;
        ///	&lt;textarea id=&quot;tryout-ta&quot; cols=&quot;50&quot; rows=&quot;20&quot;&gt;&lt;#= additionalCss #&gt;&lt;/textarea&gt;&lt;br&gt;
        ///	&lt;button onclick=&quot;add_css.innerHTML = t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string TryoutScript {
            get {
                return ResourceManager.GetString("TryoutScript", resourceCulture);
            }
        }
    }
}
