name: fpledit-ci
on:
  push:
    branches: [master,develop]
  release:
    types: [published]
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Setup .NET 6
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # v3.0.3
        with:
          dotnet-version: 6.0.x

      - name: Setup podman
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install podman

      - name: Determine build type
        if: ${{ github.event_name != 'release' }}
        run: |
          echo "FPLEDIT_GIT_BETA=1" >> $GITHUB_ENV

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Build
        run: dotnet cake --rid=linux-x64,osx-x64,win-x64,win-x86
        env:
          FPLEDIT_GIT: ${{ github.sha }}
          FPLEDIT_DOK_PDF: ./Dokumentation.pdf

      - name: Upload linux
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: fpledit-linux-x64
          path: |
            ./bin/fpledit-*-linux-*.zip
            ./bin/fpledit-*.sha256sums
          if-no-files-found: error

      - name: Upload osx
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: fpledit-osx-x64
          path: | 
            ./bin/fpledit-*-osx-*.zip
            ./bin/fpledit-*.sha256sums
          if-no-files-found: error

      - name: Upload win
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: fpledit-win
          path: |
            ./bin/fpledit-*-win-*.zip
            ./bin/fpledit-*.sha256sums
          if-no-files-found: error

      - name: Upload api-doc
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: fpledit-api-doc
          path: ./bin/api-doc/
