name: fpledit-ci
on:
  push:
    branches: [master,develop]
  release:
    types: [published]
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup .NET 6
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: 6.0.x

      - name: Setup podman
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install podman

      - name: Set beta build type
        if: ${{ github.event_name != 'release' || github.event.release.prerelease }}
        run: |
          echo "FPLEDIT_GIT_BETA=1" >> $GITHUB_ENV

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Build
        run: dotnet cake --rid=linux-x64,osx-x64,win-x64,win-x86
        env:
          FPLEDIT_GIT: ${{ github.sha }}
          FPLEDIT_DOK_PDF: ./Dokumentation.pdf

      - name: Upload zip
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: FPLedit Testversion
          path: |
            ./bin/fpledit-*-linux-*.zip
            ./bin/fpledit-*-osx-*.zip
            ./bin/fpledit-*-win-*.zip
            ./bin/fpledit-*.sha256sums
          if-no-files-found: error
          compression-level: 0 # no compression

      - name: Upload api-doc
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: fpledit-api-doc
          path: ./bin/api-doc/
